[package]
name = "lithia"
version = "0.1.0"
authors = ["JoshWhite <jwhite927@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.14.0"
unicode-width = "0.1"
termion = "1.5"
rand = "0.7"
mysql_async = "0.27.0"
tokio = { version = "1", features = ["full"] }
